# Environnement
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY 

# Services système
exec /usr/libexec/xfce-polkit
exec wl-paste --watch cliphist store

# Utilitaires
exec gammastep   
exec mako

# Tiling
exec autotiling &
