#!/bin/bash

updates="$(apt-get -q -y --ignore-hold --allow-change-held-packages --allow-unauthenticated -s dist-upgrade 2>/dev/null | grep -c ^Inst)"

if [ "$updates" -eq 0 ]; then
    alt="updated"
    text="À jour"
    tooltip="Système à jour"
    
else
    alt="has-updates"
    text="$updates"
    tooltip="$updates mises à jour disponibles"
    
    notify-send -u normal \
        --icon=update-notifier \
        "Mises à jour disponibles" \
        "$updates paquets à mettre à jour"
fi

echo "{ \"text\": \"$text\", \"alt\": \"$alt\", \"tooltip\": \"$tooltip\" }"
